### ISSUE TITLE
Service provider for Silex

### ISSUE THREAD

**Issue by teameh** [Limenius/ReactRenderer#2]
Just opening this issue to let you know that I finally put some time in open sourcing the Silex service provider I made a while ago to use the renderer in my own projects. It's only a single class, but it will help Silex users to use the renderer easily. You can find it [here](https://github.com/teameh/silex-react-renderer-provider). 

I'll add some tests and documentation soon. I'll probably largely copy and adapt the ReactBundle docs if that's okay with you.

Cheers!
BTW, I changed username: tiemevanveen -> teameh 😏

**Comment by nacmartin** [comment]
Wow! that is great :D

I will add links back to your project, it is good to have this for Silex users.

Sure, copy and adapt as much as you want, and if you have ideas about improving the docs in the process, I will be interested!

**Comment by teameh** [comment]
Awesome!

**Comment by nacmartin** [comment]
Included links in the README of the renderer (this) and the bundle.
