### ISSUE TITLE
External Server Error: Invalid or unexpected token

### ISSUE THREAD

**Issue by wajaja** [Limenius/ReactRenderer#22]
Hi!
I've configured the bundle to use an external server; when i try to refresh some page in the browser; i got this `Invalid or unexpected token`  in `eval()` function while the code in the log is 
`(function() {
    var reduxProps, context, storeGenerator, store
    reduxProps = [];
    context = {
        "serverSide":true,
        "location":"\/app_dev.php\/search\/",
        "scheme":"http",
        "port":80,
        "base":"\/app_dev.php","pathname":"\/search\/",
        "search":null
    };
    storeGenerator = ReactOnRails.getStoreGenerator('opinionStore');
    store = storeGenerator(reduxProps, context);
    ReactOnRails.setStore('opinionStore', store);
    var props = [];
    return ReactOnRails.serverRenderReactComponent({
        name: 'mainNode',
        domNodeId: 'sfreact-reactRenderer5b82edaa320b79.31532393',
        props: props,
        trace: true,
        railsContext: {
            "serverSide":true,
            "location":"\/app_dev.php\/search\/",
            "scheme":"http",
            "port":80,
            "base":"\/app_dev.php",
            "pathname":"\/search\/",
            "search":null
        },
    });
})()`

**Comment by nacmartin** [comment]
It is difficult to know, depends on what is in the external server, this external renderer should work https://github.com/Limenius/ReactRenderer/blob/master/doc/external-renderer.js

**Comment by wajaja** [comment]
its work; thank you @nacmartin you saved me

**Comment by nacmartin** [comment]
Thanks for letting us know that it worked @wajaja :D
