### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mykiwi** [Limenius/ReactRenderer#26]
This project seems to be dead as pull requests are not reviewed.

@nacmartin do you still have some time to maintain it?

**Comment by nacmartin** [comment]
@mykiwi it is maintained, it is true that I am not super responsive, but every 2-3 months I go over the issues to merge PRs, try them in the sandbox, upgrade the sandbox to the latest packages, check that everything works afterwards together and publish new releases.
