### ISSUE TITLE
AbstractReactRenderer is not guaranteed to exist

### ISSUE THREAD

**Issue by rakelley** [Limenius/ReactRenderer#28]
This is regression from #20 .
`\Limenius\ReactRenderer\Twig\ReactRenderExtension::__construct()` blindly calls `\Limenius\ReactRenderer\Renderer\StaticReactRenderer::setRenderer()` without checking if the renderer is null.  This is an intentionally nullable argument and in certain configurations (e.g. using the bundle with `default_rendering: "client_side"`) will not exist.

**Comment by IkeLutra** [comment]
I came across this as well. I will try and take a look at this and see if I can come up with a PR

**Comment by nacmartin** [comment]
Related: https://github.com/Limenius/ReactRenderer/issues/27

Yes, adding the static renderer in the presented form was a mistake. Trying to fix it in a new release.

**Comment by kodoa-dev** [comment]
Is there any workaround to this ?

**Comment by IkeLutra** [comment]
@aesislabs My workaround was to pin to `v2.1.0` which works

**Comment by VincentLanglet** [comment]
Still no update on this issue ?

**Comment by nacmartin** [comment]
Fixed in v4.
