### ISSUE TITLE
Symantec versioning containing BC breaking changes between 5.0.0 and 5.0.1

### ISSUE THREAD

**Issue by ryanolee** [Limenius/ReactRenderer#40]
# Problem
Release versions for Patch and Minor fix (https://semver.org/) level changes have been made with major BC breaks for Twig versions

# Example
Between v5.0.0 and v5.0.1 support for twig version 2 and 1 was dropped. By the looks of things this should have been a Major change given it contained changes that broke any backwards compact with older versions of symfony.

# Possible fixes 
Given v5.01 + have already been released it will be difficult to maintain any updates  between versions given it is unclear if version 5.x.x should maintain twig 2 compatibility so securitiy updates / new feature can be added in to the mainline while the current v5.1+ should be moved to v6. Or the we would want to look to maintain compatibility with twig 2 in the v4 set of releases an keep v5 as is ? 

Any thoughts @nacmartin @gempir :thinking:

**Comment by deguif** [comment]
@ryanolee support for Twig 2.x starting from 2.4 was reintroduced in master.
I'm closing this one as support for Twig 1.x is not possible while allowing Twig 2.x and 3.x (namespacing).
