### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by deguif** [Limenius/ReactRenderer#44]
It seems this project is not actively maintained currently.
There are many PRs that are open, awaiting reviews / merges.

@nacmartin if you don't have any time to maintain, would you be open for adding new maintainers?

**Comment by nacmartin** [comment]
@deguif sure, I'd like to devote more time to this project but unfortunately life keeps adding more priorities to my TODO list. Would you (or maybe someone else) want to volunteer?

**Comment by deguif** [comment]
Yes will be pleased to help maintaining this project.
I'm already involved in many other bundles / projects

**Comment by nacmartin** [comment]
Thanks for your kind offer! Invited :)
